name = "tinker-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

account_id = "8177db53d8baf69113e6102f7e635b9e"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[r2_buckets]]
binding = "TINKER_BUCKET"
bucket_name = "tinker-worker-bucket"
preview_bucket_name = "tinker-worker-bucket-dev"

[observability]
enabled = true